### ISSUE TITLE
Unable to Install CITRUS

### ISSUE THREAD

**Issue by chethanjjj** [nolanlab/citrus#101]
Hi Dr. Bruggner,

I recently am unable to install CITRUS onto my machine. I get the following error:
![screen shot 2016-09-12 at 9 39 01 pm](https://cloud.githubusercontent.com/assets/13612172/18461754/9aa24dd8-7931-11e6-8191-007ea9946593.png)
Not exactly why this is happening? Ran through your instructions another time to be sure I followed everything correctly but still the error persists.

**Comment by rbruggner** [comment]
Says the error is:

> Error: Could not find build tools necessary to build citrus

Probably means that the compiling tools are not installed properly. If you're on a mac, can you verify that XCode and the command line tools are installed correctly?

**Comment by chethanjjj** [comment]
I believe so. I installed the most up-to-date XCode and installed the command line tools via your terminal instructions.

Xcode:
Version 8

Command Tools:
![screen shot 2016-09-14 at 12 34 13 pm](https://cloud.githubusercontent.com/assets/13612172/18526968/95de3874-7a77-11e6-8ec5-1815f39492cd.png)

**Comment by rbruggner** [comment]
And if you run
`gcc -v`
... do you see the expected output?

**Comment by chethanjjj** [comment]
I believe this is correct? I am following the No OpenMP installation path
![screen shot 2016-09-17 at 7 55 14 pm](https://cloud.githubusercontent.com/assets/13612172/18612517/b0620d88-7d10-11e6-8e65-1be09fb035fb.png)

**Comment by rbruggner** [comment]
That seems correct. I'd recommend downloading the source from github and trying to install via the command line. E.G. running this in the terminal:

`R CMD INSTALL /path/to/source`

... and seeing if you get a more detailed error.

**Comment by bostendorf** [comment]
Hi chethanjjj,
it worked for me when I entered

install_github("nolanlab/citrus")

**Comment by chethanjjj** [comment]
@bostendorf that's interesting. are you running the most up-to-date Xcode?

**Comment by bostendorf** [comment]
yes, I'm running Xcode 8.0

**Comment by rbruggner** [comment]
@chethanjjj I'm closing this as stale - please feel free to re-open if still a problem.

**Comment by chethanjjj** [comment]
Hope all is well. I have a question regarding the CITRUS installation #2. I was able to install it properly thanks to your suggestions, however....

It seems using this method causes problems with other R packages (flowStats) in the meta-analysis framework I showed you earlier in summer.

I’ve tried using the first installation step but came across the issues you had mentioned in a thread. The solution I’ve been told is to compile all R packages using gcc instead of the default compilers/using the binary packages. Before I do this, I’m just wondering if you have any suggestions to make CIRTUS play nicely with the other packages.

- Chethan Jujjavarapu

**Comment by rbruggner** [comment]
I've had relatively minimal experience exposure to this, but I think I recall experiencing something similar to you - that is: R tends to be very unstable if you use packages that have C/C++ code that were compiled using different compilers, particularly if there are dependencies between the packages. 

For example, if you install the Rcpp binary from cran (which is compiled with clang) and then locally compile RClusterpp that links to Rcpp with g++, R crashes a lot. My workaround was to explicitly build all the packages I was using from source (e.g. compile both Rcpp and RClusterpp using the g++ compiler on my machine) in order to ensure compatibility. 

Not sure if that helps you out at all, but might be worth giving a shot.

**Comment by chethanjjj** [comment]
No that makes sense. You're confirming it's necessary to compile all relevant packages for the pipeline using gcc

**Comment by miriamsand** [comment]
Hi, I'm running R Version 1.1.442 on MacOS high Sierra 10.13.3. I have downloaded Command line tools, and can't download citrus. When downloading, I still get "Installation failed: Could not find build tools necessary to build citrus". Thereafter I get redirected to downloading command line tools - again. Any tips? 

<img width="797" alt="skjermbilde 2018-04-20 kl 17 21 47" src="https://user-images.githubusercontent.com/38564631/39059754-b4c94e54-44bf-11e8-8269-9e14df2f55f6.png">

**Comment by rbruggner** [comment]
Can you post a screenshot that shows the errors you’re encountering in R, please?
