### ISSUE TITLE
Cannot install Citrus

### ISSUE THREAD

**Issue by liyan99** [nolanlab/citrus#102]
rary("devtools")
> install_github('citrus',username='nolanlab')
Downloading GitHub repo nolanlab/citrus@master
from URL https://api.github.com/repos/nolanlab/citrus/zipball/master
Installing citrus
"//adc3/roam$/li99/MYDOCU~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/li99/AppData/Local/Temp/RtmpOwRdUI/devtools1930600bbcf/nolanlab-citrus-05b0b62"  \
  --library="\\adc3/roam$/li99/My Documents/R/R-3.3.1/library"  \
  --install-tests 

'\\adc3\roam$\li99\MYDOCU~1\R\R-33~1.1' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use nolanlab/citrus 
> install_github('citrus',username='nolanlab/citrus')
Downloading GitHub repo nolanlab/citrus/citrus@master
from URL https://api.github.com/repos/nolanlab/citrus/citrus/zipball/master
Error in stop(github_error(request)) : Not Found (404)
In addition: Warning message:
Username parameter is deprecated. Please use nolanlab/citrus/citrus 
> library("citrus")
Error in library("citrus") : there is no package called ‘citrus’
>

**Comment by liyan99** [comment]
Please help me take a look, I have tried several times, but there always an error. Thanks a lot

**Comment by rbruggner** [comment]
The paths and messages that you have posted here suggest that you have a non-standard R installation and configuration that is causing the installation to fail. Given the appearance of a custom install/configuration, it is unlikely that I will be able to help you fix the problem. 

The best I can suggest would be to perform a clean, local install of R and development tools and see if that enables you to install.

**Comment by liyan99** [comment]
Thanks a lot. I am going to uninstall my R and reinstall it.

**Comment by liyan99** [comment]
I have reinstall the R but it is still the same problem. I used the lab computer that usually saved my files on the public disk. Is it possible that my R is not in my local computer, so the R and citrus are not saved in the same path, therefore they can not find each other? But when I install the R, I choose all of them as default. Thanks a lot.

**Comment by liyan99** [comment]
The downloaded binary packages are in
        C:\Users\li99\AppData\Local\Temp\RtmpQTSZAF\downloaded_packages
> install.packages("samr")
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/samr_2.0.zip'
Content type 'application/zip' length 122310 bytes (119 KB)
downloaded 119 KB

package ‘samr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\li99\AppData\Local\Temp\RtmpQTSZAF\downloaded_packages
> install.packages("shiny") # For GUI
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/shiny_0.14.1.zip'
Content type 'application/zip' length 2648327 bytes (2.5 MB)
downloaded 2.5 MB

package ‘shiny’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\li99\AppData\Local\Temp\RtmpQTSZAF\downloaded_packages
> install.packages("brew")  # For GUI
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/brew_1.0-6.zip'
Content type 'application/zip' length 104721 bytes (102 KB)
downloaded 102 KB

package ‘brew’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\li99\AppData\Local\Temp\RtmpQTSZAF\downloaded_packages
> mkdir ~/.R
Error: unexpected '/' in "mkdir ~/"
> echo "CXX=c++ -arch x86_64" >> ~/.R/Makevars
Error: unexpected string constant in "echo "CXX=c++ -arch x86_64""
> install.packages("devtools")
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/devtools_1.12.0.zip'
Content type 'application/zip' length 432097 bytes (421 KB)
downloaded 421 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\li99\AppData\Local\Temp\RtmpQTSZAF\downloaded_packages
> library("devtools")
> install_github('citrus',username='nolanlab')
Downloading GitHub repo nolanlab/citrus@master
from URL https://api.github.com/repos/nolanlab/citrus/zipball/master
Installing citrus
"//adc3/roam$/li99/MYDOCU~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/li99/AppData/Local/Temp/RtmpQTSZAF/devtools18e8347e590f/nolanlab-citrus-a0ab57a"  \
  --library="\\adc3/roam$/li99/My Documents/R/R-3.3.1/library"  \
  --install-tests 

'\\adc3\roam$\li99\MYDOCU~1\R\R-33~1.1' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use nolanlab/citrus 
> library("citrus")
Error in library("citrus") : there is no package called ‘citrus’
>

**Comment by rbruggner** [comment]
Again, the custom nature of your environment makes it difficult for me to assist here, but I can say the the key error failure is:

> '\adc3\roam$\li99\MYDOCU~1\R\R-33~1.1' is not recognized as an internal or external command,
operable program or batch file.

The command that's attempting to install Citrus is looking for the R binary / executable and the path seems to be incorrect. You will not be able to install citrus without getting the execution paths resolved. 

This problem could possibly be caused by an incorrect installation and configuration of the windows RTools binaries.

**Comment by liyan99** [comment]
I reinstall R directly under C disk, then I figured it out. Thanks a lot.

**Comment by rbruggner** [comment]
Ah - great to hear.
