### ISSUE TITLE
question on citrus output

### ISSUE THREAD

**Issue by elenaven** [nolanlab/citrus#104]
After running citrus, the hierarchical tree seems to be divided into 3 groups of clusters (see annotated figure). 
Can you clarify what these 3 subgroups may be? Are these just similar clusters? Why are they grouped togeher?
![citrus image](https://cloud.githubusercontent.com/assets/19414484/19591316/b1c3a738-9776-11e6-8477-e793fe3686ba.png)

**Comment by rbruggner** [comment]
I can't be quite sure, but this appears to be a figure from a paper. I would recommend contacting the paper authors to interpret this figure.

**Comment by elenaven** [comment]
I am the one trying to submit the paper.
The figure was made like that by citrus and I was trying to better understand the output, so I can properly describe it.
Do you know why citrus groups some of the clusters together with outer circles?
Thanks!
Elena

Sent from my iPhone

On Oct 21, 2016, at 9:39 PM, Robert Bruggner <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't be quite sure, but this appears to be a figure from a paper. I would recommend contacting the paper authors to interpret this figure.

-

**Comment by rbruggner** [comment]
Yes - Citrus produces a plot with the clustering hierarchy and encircles all the nodes where any one specific feature is found to be significant. You should get a separate plots of the clustering hierarchy with clusters encircled for each significant feature (e.g. abundances, channel X median, channel Y median). 

Aside, I would recommend potentially not using that plot in your manuscript if you are unclear how those circles pertain to your results. Perhaps one of the other plots that Citrus makes may better support your conclusions?

**Comment by elenaven** [comment]
Thank you very much! I had reached the same conclusion, but wanted to double check I understood the plot correctly, since I couldn't find a good description of the encircling feature anywhere.
Appreciate the help!

Elena

Sent from my iPhone

On Oct 25, 2016, at 8:40 PM, Robert Bruggner <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes - Citrus produces a plot with the clustering hierarchy and encircles all the nodes where any one specific feature is found to be significant. You should get a separate plots of the clustering hierarchy with clusters encircled for each significant feature (e.g. abundances, channel X median, channel Y median).

Aside, I would recommend potentially not using that plot in your manuscript if you are unclear how those circles pertain to your results. Perhaps one of the other plots that Citrus makes may better support your conclusions?

-
