### ISSUE TITLE
Unable to install Citrus

### ISSUE THREAD

**Issue by amirmku** [nolanlab/citrus#107]
After installing all the prerequisite module as asked when I finally tried installing Citrus in R
>**install_github('nolanlab/citrus')**
it showed me an error
"Downloading github repo nolanlab/citrus@master
Installing citrus
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/5l/qhqdkfxj1hb135tl_d7vqlv40000gr/T/RtmpNHmscc/devtools40c243c58382/nolanlab-citrus-a0ab57a'  \
  --library='/Library/Frameworks/R.framework/Versions/3.0/Resources/library'  \
  --install-tests 

* installing *source* package ‘citrus’ ...
** libs
c++ -arch x86_64 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include   -I../inst/include  -fPIC  -mtune=core2 -g -O2  -c upsample.cc -o upsample.o
c++ -arch x86_64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/lib -L/usr/local/lib -o citrus.so upsample.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.0/Resources/library/citrus/libs
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.0/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.0/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /usr/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.0/Resources/library/rgl/libs/rgl.so
  Reason: image not found
Error : package ‘flowCore’ could not be loaded
ERROR: lazy loading failed for package ‘citrus’
* removing ‘/Library/Frameworks/R.framework/Versions/3.0/Resources/library/citrus’
Error: Command failed (1)"

Can I anyone help me in resolving the issue

**Comment by rbruggner** [comment]
Have you installed XQuartz? 
http://stackoverflow.com/questions/9878693/error-in-loading-rgl-package-with-mac-os-x

**Comment by amirmku** [comment]
Hi Thanks a lot, after installing Xquartz, I could get citrus. However when I am trying to launch using command > citrus.launchUI()
it opened a popup window (not sure, what to do next to open GUI of Citrus) and also display loading required package parallel
loading required package reshape2
Please find the snapshot attached.
Sorry I am totally naive to coding so really dont understand what does these command mean.
Would highly appreciate your help in resolving this issue further.


![screen shot 2016-11-13 at 7 51 38 pm](https://cloud.githubusercontent.com/assets/23407547/20250271/cd717ad4-a9da-11e6-868e-92f2aafaf7da.png)

**Comment by rbruggner** [comment]
That looks like it’s functioning correctly. Please follow the usage guide for directions on how to proceed: https://github.com/nolanlab/citrus/wiki/Getting-Started#Starting_a_Citrus_analysis <https://github.com/nolanlab/citrus/wiki/Getting-Started#Starting_a_Citrus_analysis>
