### ISSUE TITLE
FlowCAP-I setup

### ISSUE THREAD

**Issue by hl475** [nolanlab/citrus#108]
Hi I have a question regarding the set-up of citrus for FlowCAP-I mentioned in the paper 'Automated identification of stratifying signatures in cellular subpopulations'.

Do you do any kind of transformation or scaling when you read the data? For example, the GvHD dataset, I did the following according to Table S2 of the[ paper ](http://www.pnas.org/content/111/26/E2770.abstract?tab=ds)
```
clusteringColumns = c("FL1.H","FL2.H","FL3.H","FL4.H")
citrus.combinedFCSSet = citrus.readFCSSet(dataDirectory, fileList, fileSampleSize = 10000)

citrus.clustering = citrus.cluster(citrus.combinedFCSSet, clusteringColumns)
largeEnoughClusters = citrus.selectClusters(citrus.clustering,
                                            minimumClusterSizePercent = .05)
```
citrus.combinedFCSSet contains 12 * 10000 = 120000 events. I didn't get length(largeEnoughClusters) = 46 as said in column 3 Table S2 for GvHD. I have also tried with specifying transformColumns, transformCofactor, scaleColumns.

What do I miss here? How should I set up the experiment to get length(largeEnoughClusters) = 46 as said in column 3 Table S2 for GvHD? Thanks!

**Comment by rbruggner** [comment]
I believe column 3 of summary table S2 the total number of manually identified populations in the FlowCap1 GvHD dataset. That is, there are 12 files, with say 3 to 4 manually identified populations in each of the files = about 46 populations. That table does not refer to the number of populations identified by Citrus.
