### ISSUE TITLE
Export FCS events for manual examination

### ISSUE THREAD

**Issue by SamGG** [nolanlab/citrus#109]
Hi,
Do you know any piece of code to export the events of a cluster identified by its number?
Best.

**Comment by rbruggner** [comment]
https://github.com/nolanlab/citrus/wiki/Citrus-FAQ#How_do_I_export_data_from_specific_clusters <https://github.com/nolanlab/citrus/wiki/Citrus-FAQ#How_do_I_export_data_from_specific_clusters>

**Comment by SamGG** [comment]
Thanks, I read the tuto but not the FAQ.
In the first prargraph of the FAQ, I think you are talking about FlowJo, with a w, not FloJo.
Best.

**Comment by rbruggner** [comment]
Haha. Yes! You are right :) Spelling not my strong suit.

**Comment by rbruggner** [comment]
Florence Griffith Joyner? Not even close :)

**Comment by SamGG** [comment]
I did the same query and got the same answer. You read in my mind.
