### ISSUE TITLE
citrus.exportCluster() add option to export raw data?

### ISSUE THREAD

**Issue by bc2zb** [nolanlab/citrus#111]
I'm running a lot of analyses for cytometrists and they want to look at the results in FlowJo or FCS express. However, citrus only appears to export the transformed data, is it possible to have citrus export the untransformed data?

**Comment by rbruggner** [comment]
My understanding is that citrus should be untransforming data before exporting. 
https://github.com/nolanlab/citrus/blob/master/R/citrus.util.R#L437

I believe there could be a bug - could you create a reproducible case?

**Comment by bc2zb** [comment]
Thanks for responding. Appears to not be an issue at all. Sorry I didn't vet it further before bringing it here. All the data citrus exported does fall within the range of the original data, it does appear to be "raw".
