### ISSUE TITLE
producing "white" theme plots with citrus.full()

### ISSUE THREAD

**Issue by cjungR** [nolanlab/citrus#116]
Hello,

Is there a way to produce white themed plots using `citrus.full()`? Ie with the "runCitrus.R" that is produced after running `citrus.launchUI()`.  Plotting the results from `citrus.fill()` will produce a plot with a black background by default. It would also be great to have an option to select the white theme with `citrus.launchUI()`.

**Comment by rbruggner** [comment]
Unfortunately not currently possible to configure using `citrus.full()`. 

If you need the white background, I'd suggest using the UI to run the program, find the configuration you want, and then you can run the same configuration manually and specify the white theme. See the documentation for `citrus.plotHierarchicalClusterFeatureGroups` as an example.
