### ISSUE TITLE
Cross Validation Folds is sticked to 1

### ISSUE THREAD

**Issue by SamGG** [nolanlab/citrus#121]
Using UI v0.8, Cross Validation Folds is constantly reset to 1 although the file count is 16 in my case. I think it's due to the way this field is initiated, ie programmatically. There seems to be a trigger that call this reset even when I try to increment it simply.
Best.

**Comment by SforR** [comment]
Hi,

The problem looks similar to the case #75 "not possible to change number of cross-validation folds in UI (Mac)". Am I right? 

Best,

Sam

**Comment by SamGG** [comment]
Correct! I didn't double check :-(

**Comment by JING202** [comment]
> Correct! I didn't double check :-(
> It's a shiny problem, not a Mac specificity this time.
Hi,
I have the same problem using UI v0.8 in Wins. Is there any way to change CVF?

**Comment by JING202** [comment]
Hi,
I have the same problem using UI v0.8 in Wins. Is there any way to change CVF?
