### ISSUE TITLE
Installing citrus on Windows

### ISSUE THREAD

**Issue by cmartinezfleites** [nolanlab/citrus#123]
Hello,

When trying to install citrus on windows/Rstudio I get the following error ,

> devtools::install_github('nolanlab/citrus')
Downloading GitHub repo nolanlab/citrus@master
from URL https://api.github.com/repos/nolanlab/citrus/zipball/master
Installing citrus
Installation failed: cannot open the connection
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users\cm355973\Downloads\plyr-master\plyr-master": The system cannot find the path specified
2: In read.dcf(path) :
  cannot open compressed file 'C:\Users\cm355973\Downloads\plyr-master\plyr-master/DESCRIPTION', probable reason 'No such file or directory'

is there any way to correct this?

Many thanks

Carlos Martinez

**Comment by cmartinezfleites** [comment]
Hi SamGG,

b) does it and citrus installs ok.
thank you very much,

cmartinezfleites

**Comment by SamGG** [comment]
Happy Citrus!
PS: close the issue.
