### ISSUE TITLE
Feature calculation takes too long

### ISSUE THREAD

**Issue by cbligaard** [nolanlab/citrus#127]
Hi Citrus-team,

I have an experiment with a 120 CyTOF files and I would like to run Citrus to analyze them. I can manage to get through the clustering by downsampling, but the `citrus.calculateFoldFeatureSet` just never finishes for me (I have given it more than 24 hours). Do you have any suggestions for how I can get beyond this?

Best, 
Christina

**Comment by rbruggner** [comment]
Hi Christina, 

Is the CPU "doing something" during that long runtime (e.g. is it still calculating features/values) or is the related CPU usage "zero" when the program appears to be running definitely?
