### ISSUE TITLE
running citrus

### ISSUE THREAD

**Issue by nncytof** [nolanlab/citrus#78]
Hi, 
I'm trying to run Citrus using the instructions listed on this website: https://github.com/nolanlab/citrus/wiki/Installing-Citrus#Installation
I am not sure how to input the following code into R:
 shell> mkdir ~/.R
 shell> echo "CXX=c++ -arch x86_64" >> ~/.R/Makevars

Also, when I type the following code, I get this message: Username parameter is deprecated. Please use nolanlab/citrus. 
 R> install.packages("devtools")
 R> library("devtools")
 R> install_github('citrus',username='nolanlab')

Wondering if you could help me to resolve this problem?
Thank you!

**Comment by mehrdad-shirangi** [comment]
I am facing the same issue... anyone can help with this? 
Thank you

**Comment by rbruggner** [comment]
Hi all, 

For your first question, the commands that are preceded by the words ```shell>``` should be entered into a terminal prompt (shell), not in R. To enter, open the terminal application and enter the commands following the ```shell>```. 

WRT the second question about the installation warning,  I don't think that causes installation to fail, but if it does, try the command:

install_github("nolanlab/citrus") 

... instead.
