### ISSUE TITLE
No output in sam_results

### ISSUE THREAD

**Issue by bc2zb** [nolanlab/citrus#80]
When sourcing the runCitrus.R file generate by the GUI. Nothing prints to the sam_results directory, and only markerPlots.pdf and markerPlotsAll.pdf are being outputted by the script. Is this the expected behavior?

**Comment by shenorr** [comment]
Yes if no diiferencrs noted by fdr of 10%

**Comment by bc2zb** [comment]
Thanks for the quick response. One other question, what is the significance of the following error? I have not encountered it before, and can't seem to find anyone else who has either.

Error in ttstar[, j] <- -1 * sort(-1 * ttstar[, j]) : 
  replacement has length zero

**Comment by shenorr** [comment]
By the look of the code this is an error internal to SAM - what did you try
to do?

**Comment by bc2zb** [comment]
I ran the code at the bottom of the runCitrus.R file. The section with the heading below:

# ==================================================================================================
# The following lines perform the same analysis as the citrus.full() function but broken down
# into component steps. This is may be more useful to run if you plan on running the clustering
# once but examining many endpoints, features, or minimum cluster sizes. You should uncomment 
# the clustering, feature extraction, regression, and plotting functionlines. 
# ==================================================================================================

I uncommented the places where appropriate. The error comes up whenever I run the following command from the script:

citrus.regressionResults = mclapply(modelTypes,citrus.endpointRegress,citrus.foldFeatureSet=citrus.foldFeatureSet,labels=labels,family=family)

I will have many cytof runs coming across my desk, so I am trying to build a pipeline with Citrus. The GUI is very nice but would not work well for my pipeline.
