### ISSUE TITLE
Can't start GUI on linux

### ISSUE THREAD

**Issue by nehcgnay** [nolanlab/citrus#85]
Hello, 

I would like to run citrus on a remote linux server. However, it shows the following messages instead of popping up the window. Any suggestions?

> citrus.launchUI()
Attaching package: ‘shiny’
The following objects are masked from ‘package:R.utils’:
    setProgress, validate
Enter file name:

I have X11 forwarding configured and it's working well on other softwares such as matlab.

Thank you in advance!

**Comment by rbruggner** [comment]
The citrus GUI operates through a web browser and it might be the case that R may not have the permissions to start a new X11 program (like your browser) for various security reasons. 

The "enter file name" prompt is asking you for the path to one (any) fcs file in then directory of fcs files that you wish to analyze. Try entering the full path to one of those fcs files at the prompt.

It may then tell you that the Citrus GUI is then running at say http://<hostname>:<port> 

At that point, you should be able to open a web browser on your local machine or your remote machine (via X11 forwarding) and point it at the URL above to access the GUI.

**Comment by nehcgnay** [comment]
Thank you for your reply! I tried entering the full path but then it shows:

Scanning parameters in FCS files
Reading parameters in 1.fcs
Error in value[[3L]](cond) : 
  Unexpected Error: Error in value[[3L]](cond): object 'splitInt' not found

**Comment by rbruggner** [comment]
I think this error is related to the flowCore package not being able to read your FCS file, not a problem with Citrus. 

Try loading the flowCore package and seeing if you can read your FCS file using the read.FCS() function. If that fails, there might be something wrong with your FCS files.

**Comment by nehcgnay** [comment]
Thanks a lot! It was a bug in flowCore, which is solved in ver  1.36.1.
