### ISSUE TITLE
Vast majority of Time column is populated with "1024" from citrus.exportClusterUI() output

### ISSUE THREAD

**Issue by bc2zb** [nolanlab/citrus#86]
I exported clusters from my citrus analysis and almost every event's Time column is 1024. For one cluster, 16065 events have a Time value of 1024, and then 8 events have what appear to be real time values. After using the UI to export the clusters into a directory, I read in all the files to create a flowSet object. Looking at the flowFrame for each sample for each cluster reveals the odd Time value assignment.

**Comment by rbruggner** [comment]
There appears to be some strange default behavior in the write.FCS function of flowCore that truncates channel ranges to 1024. I've written a post to bioconductor asking if that's expected behavior or a bug.

https://support.bioconductor.org/p/75380/
