### ISSUE TITLE
gcc48 issue

### ISSUE THREAD

**Issue by chethanjjj** [nolanlab/citrus#91]
installed Citrus, however it crashed my RStudio anytime I ran it, so I followed your directions to install Citrus using MacPorts with g++4.8, however after running the following code:

> sudo port install gcc48

I got the following error:

> Error: org.macports.build for port gcc48 returned: command execution failed
Please see the log file for port gcc48 for details:
/opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_lang_gcc48/gcc48/main.log
To report a bug, follow the instructions in the guide:
http://guide.macports.org/#project.tickets
Error: Processing of port gcc48 failed

After reading forums, the error seems to be involved with the updated Mac OS Software: El Capitan. Do you have any thoughts about a way around this?

I've also included my terminal commands in a text file attachment, so you can see exactly what happened

[Log at 2016-01-18 23.17.34.txt](https://github.com/nolanlab/citrus/files/95482/Log.at.2016-01-18.23.17.34.txt)

**Comment by rbruggner** [comment]
I was able to replicate this issue, but really don't have a good suggestion at the moment for working around the problem. Have you tried installing / using another version of GCC - say 4.9? 

I have no idea if that would work, but that's the only thing that comes to mind immediately.

**Comment by SamGG** [comment]
Did you look at https://trac.macports.org/ticket/48471? They report also their trials in getting higher versions of gcc, but BLAS seems to require 4.8. It seems (3h ago) to be fixed in Xcode 7.3, but I don't have any Mac...

**Comment by chethanjjj** [comment]
I tried 4.9 and citrus installed without a problem and didn't crash when I used it, so it seems to be working fine.

**Comment by chethanjjj** [comment]
Thank you for taking the time to review this problem, Dr. Bruggner.

**Comment by chethanjjj** [comment]
Hi Dr. Bruggner,

After following your suggestion about gcc49, I found that flowStats and openCyto (bioconductor packages) would crash whenever I tried to load them.

I traced this issue to the following line of code:
`install.packages(c("Rcpp","RcppEigen","Rclusterpp"),type="source")`

FlowStats and openCyto will only work properly if I install the binary packages or install the source packages via the clang++ compiler.

so now my temporary solution to use flowStats/openCyto and CITRUS is to recompile these packages with gcc49 for CITRUS and clang++/use binary packages for flowStats/openCyto.

Do you have any possible solution, so that I won't have to do this?

**Comment by rbruggner** [comment]
As @SamGG mentioned (thanks!), this issue might be fixed in Xcode 7.3 (as per this comment https://trac.macports.org/ticket/48471#comment:92). If you download and install Xcode 7.3 (https://developer.apple.com/xcode/download/), it might enable you to install GCC 4.8 which I believe would resolve the crashes. 

However, I have not verified that installing XCode 7.3 does indeed fix the problem with installing GCC 4.8.

**Comment by chethanjjj** [comment]
i see. hmmm ok. well when I get a chance I will test this out and get back to you guys!

**Comment by rbruggner** [comment]
Apple just officially released XCode 7.3 today. I installed it and confirmed that you can now properly build GCC 4.8 from mac ports.

**Comment by chethanjjj** [comment]
Oh sweet. Thanks Rob!

- Chethan Jujjavarapu
