### ISSUE TITLE
Properties for cluster characterization

### ISSUE THREAD

**Issue by nehcgnay** [nolanlab/citrus#92]
Hello, 

I found the latest version doesn't allow to choose both abundance and median but only one of them for  cluster characterization. Is this a bug of the GUI or changed with purpose? 

Thank you in advance!

**Comment by rbruggner** [comment]
This is by design, to make interpretation of results easier. However, if you'd like to include both median and abundance features in your model, you can always modify the runCITRUS.R file that the GUI creates and run that code directly.

**Comment by nehcgnay** [comment]
Thank you for the quick reply!
