### ISSUE TITLE
Comparison not including Citrus

### ISSUE THREAD

**Issue by SamGG** [nolanlab/citrus#96]
Hi Robert,
If you have time to read 
Comparison of Clustering Methods for High-Dimensional Single-Cell Flow and Mass Cytometry Data
Lukas M Weber, Mark D Robinson
doi: http://dx.doi.org/10.1101/047613

**Comment by rbruggner** [comment]
Oh, interesting. I'll take a look and will comment.  Thank you for the ref.

**Comment by rbruggner** [comment]
Just had a look, and added the following comment: 

> Very cool comparison guys! Nice to see this sort of rigor and systematic approach to this problem.

> A couple of thoughts that probably don't change your conclusions substantially:

> FWIW, the "Wards" linkage method as implemented in Rclusterpp runs much faster and produces better clustering results (than the average / euclidian combo) by my previous evaluations. I just clustered all events in the 2015 Levine Marrow 32 dataset on my 2013 Macbook (4 cores) in about 25 minutes.

> The "standard" hierarchical clustering methods that Rclusterpp implements are not tuned or designed specifically for flow cytometry data + the population identification problem and I believe many of the methods in your comparison are. In some sense, this sort of presents an "apples to oranges" comparison situation. At the very minimum though, it is a really nice demonstration of how much better domain-tuned algorithms perform relative to generalized clustering algorithms. In that respect, I think there are some useful adaptations of hierarchical clustering that make it better suited to flow cytometry work, but obviously I'm biased :)

And specifically, the adaptation that I'm referring to is using to use all the clusters identified in the clustering hierarchy rather than cutting the tree at a fixed point and using the terminal clusters. 

Thank you for pointing my direction!
