### ISSUE TITLE
installation problem over https

### ISSUE THREAD

**Issue by andersoa** [nolanlab/citrus#97]
I am trying to install citrus in an environment that blocks access to https via curl and this prevents me from successfully following the citrus installation instructions. Downloading the zip file directly and trying to install from it within RStudio also fails. 

> install_github('citrus',username='nolanlab')
Downloading GitHub repo nolanlab/citrus@master
from URL https://api.github.com/repos/nolanlab/citrus/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates
In addition: Warning message:
Username parameter is deprecated. Please use nolanlab/citrus 

Getting zip file from  https://api.github.com/repos/nolanlab/citrus/zipball/master and installing it directly...

> install.packages("nolanlab-citrus-v0.8-0-g0d308ab.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
  cannot open compressed file 'nolanlab-citrus-v0.8-0-g0d308ab/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

Renaming one of the internal folders to match the zipfile name allows a partial install but the package cannot be found...
> install.packages("nolanlab-citrus-v0.8-0-g0d308ab.zip", repos = NULL, type = "win.binary")
> library("citrus")
Error in library("citrus") : there is no package called ‘citrus’

**Comment by rbruggner** [comment]
To the best of my knowledge, there's no pre-compiled binary version of citrus available (for windows or mac).  I think in this circumstance, you'll need to download the source and then build and install. 

Have you tried something like: 
`install.packages(LOCAL_PATH_TO_CITRUS_SOURCE, repos = NULL, type="source")`
?

**Comment by andersoa** [comment]
No, I tried something with a different "type"
install.packages("nolanlab-citrus-v0.8-0-g0d308ab.zip", repos = NULL, type = "win.binary")
..and this didn't work.

The issue is now resolved. The problem was with my company's URL filtering and security service. This has been modified, and I have completed to the installation.
Thanks.
