### ISSUE TITLE
Error message after harmonizing files

### ISSUE THREAD

**Issue by elenaven** [nolanlab/citrus#98]
Hello, 

I am trying to run CITRUS on files that I have harmonized using cytofCore. 
When I try to open the GUI, the following error message appears:
"Error in value[[3L]](cond) : 
  Unexpected Error: Error in value[[3L]](cond): $PnRNaNis larger than R's numeric limit:1.79769313486232e+308"

Any help would be appreciated!
Thanks!
Elena

**Comment by rbruggner** [comment]
Hi Elena,

Unfortunately, it sounds like the FCS file parameters (specifically the range parameters) has not been set correctly. There's nothing Citrus can do about this - will need to figure out why those parameters are corrupted in your input files.

-R

**Comment by elenaven** [comment]
Hi Robert,

Thank you for your email.
I can try to play with the FCS files, and see if it’s something I did that corrupted them.
If you have any specific suggestions, let me know!

Elena

On Jun 22, 2016, at 3:35 PM, Robert Bruggner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Elena,

Unfortunately, it sounds like the FCS file parameters (specifically the range parameters) has not been set correctly. There's nothing Citrus can do about this - will need to figure out why those parameters are corrupted in your input files.

-R
